application: soumyajitnayakweb 
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*\.html)
  static_files: \1
  upload: (.*\.html)

- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)

- url: /.well-known/(.*)
  static_files: well-known/\1
  upload: well-known/(.*)

- url: /docs/(.*)
  static_files: docs/\1
  upload: docs/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /(.*\.html)
  static_files: \1
  upload: index.html